### PR TITLE
Successful build on OS X 10.13.4

### PR DESCRIPTION
**Pull request by elliottjohnson**
With the following modifications, I was able to successfully build on mac os x 10.13.4.
The README instructions work as described and I'm getting correct MIDI events from my Roland PC-300.

### CODE REVIEW

**Comment by elliottjohnson** [comment]
Oh I should note that I'm using Xcode 9.3.

**Comment by ysalathe** [comment]
Unfortunately, I no longer own a PC300. Thus, I cannot test these changes. Is somebody interested in taking over the project?

**Comment by ignat980** [comment]
The changes work! One note though, the plugin won't load if there is another plugin that is 32-bit only. Had to watch console for a bit before I noticed that. I'm no driver expert, so I'm not sure how to modify the build settings so that it works alongside 32-bit plugins as well, or if it is a code issue, but otherwise works just fine. It seems like the settings are set up to build for both architectures... but oh well, no biggie, I can just move those other plugins back in if I need to. Thanks

**Comment by setton1** [comment]
@ignat980 I am a bit of a noob...how did you get the changes to work on Mojave? appreciate your help!

**Comment by clysss** [comment]
hello,
could you provide directly the .plugin in github (without having to compilate?) 
It will help to test rapidly ! (I still own this keyboard pc-300, but not using it on mac .. but I can test if needed!)

**Comment by ignat980** [comment]
@setton1 I was still on High Sierra when I had built it! I currently do not have easy access to a MIDI keyboard atm, and had updated to Mojave just now, so I cannot say for sure that the plugin still works. I had a few drawing pen tablet plugins fail, but I don't see why the MIDI keyboard plugin wouldn't work on Mojave. Can you share a pastebin of your console log with all the MIDI message notifications, to see if any error are popping up, or if the plugin is being loaded at all?

**Pull request merged**
